# Number of lines
NB_LINES = 15
NB_COLUMN = 15

# Window dimension

WINDOW_LENGTH = 600
WINDOW_HEIGHT = 600

# Case dimension
CASE_LENGTH = WINDOW_LENGTH // NB_LINES
CASE_HEIGHT = WINDOW_HEIGHT // NB_COLUMN

POSITION_WALL = (0, 0)
POSITION_PIXEL_DEAD = (0, 0)
POSITION_PIXEL_WIN = (0, 0)
